# Generated by Django 5.1.5 on 2025-03-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Join_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
    ]
